#!/usr/bin/ruby

# /etc/init.d/buildmenu

# :MC: this depends on the hostname being set.
# tweak /etc/init.d/hostname.sh to set the host names

shutdown = 'echo "-------"; echo "Press enter to shutdown..."; read pause; poweroff -f'

hostname = `hostname`.chomp

newdisktest = "/usr/bin/disktest"

disktest = "echo '*.* /var/log/kmsg.pipe' >> /etc/syslog.conf ; invoke-rc.d sysklogd restart ; /usr/bin/diag-disk"

timeout = false

if ENV['DEFAULT_MENU']
    default = ENV['DEFAULT_MENU']
    timeout = 10
elsif /test/.match(hostname)
    timeout = 5
    default = "new disk test"
else
    exit
end

require 'rubytui'
include RubyTUI

$TIMEOUT = timeout

cloner = '/usr/local/bin/lessdisks-cloner'

choice = menuWithDefault("build boot options","choose a boot option",default,
    "diskless terminal", "new disk test", "disk test", "root", "Video Card Detector", "keyboard tester")

case choice
when "new disk test"
    system "#{newdisktest} || bash"
when "disk test"
    system "#{disktest} || bash"
when "diskless terminal"
    # do nothing
    exit
when "root"
    system "/bin/bash"
when "Video Card Detector"
    system "/usr/bin/openvt -- /bin/bash --login"
    system "/usr/bin/video-detect || bash"
when "keyboard tester"
    system "/usr/bin/xinit /usr/bin/wx-keyboard-tester"
end

system shutdown
