#!/usr/bin/ruby

# /etc/init.d/buildmenu

# :MC: this depends on the hostname being set.
# tweak /etc/init.d/hostname.sh to set the host names

# buildmenu will exit unless either $DEFAULT_MENU is set or the
# hostname is set and includes the word "test" (for disktesting).

shutdown = 'echo "-------"; echo "Press enter to shutdown..."; read pause; poweroff -f'

hostname = `hostname`.chomp

newdisktest = "/usr/bin/disktest"

timeout = false

if ENV['DEFAULT_MENU']
    default = ENV['DEFAULT_MENU']
    timeout = 10
elsif /test/.match(hostname)
    timeout = 5
    default = "new disk test"
else
    exit
end

require 'rubytui'
include RubyTUI

$TIMEOUT = timeout

choice = menuWithDefault("build boot options","choose a boot option",default,
    "diskless terminal", "new disk test", "disk test", "root", "Video Card Detector", "keyboard tester", "Proc DB Detection")

def start_shell
    system "/usr/bin/openvt -- /bin/bash --login"
end

case choice
when "new disk test"
    start_shell
    system "#{newdisktest} || bash"
when "diskless terminal"
    # do nothing
    exit
when "root"
    system "/bin/bash"
when "Video Card Detector"
    start_shell
    system "/usr/bin/video-detect || bash"
when "keyboard tester"
    system "/usr/bin/xinit /usr/bin/wx-keyboard-tester"
when "Proc DB Detection"
  system "/usr/sbin/lookup-cpu"
end

system shutdown
