#!/bin/bash

config_file="/usr/local/ass/configs/build/netboot_update_config"

while read DISTRO CODENAME; do
    cd /tmp
    if [[ $DISTRO == "ubuntu" ]]; then
	wget http://archive.ubuntu.com/ubuntu/dists/$CODENAME/main/installer-i386/current/images/netboot/netboot.tar.gz
    fi
    if [[ $DISTRO == "debian" ]]; then
	wget http://ftp.debian.org/dists/$CODENAME/main/installer-i386/current/images/netboot/netboot.tar.gz
    fi
    [ -d /var/lib/tftpboot/$DISTRO-installer/$CODENAME.old ] && rm -fr /var/lib/tftpboot/$DISTRO-installer/$CODENAME.old
    [ -d /var/lib/tftpboot/$DISTRO-installer/$CODENAME ] && mv /var/lib/tftpboot/$DISTRO-installer/$CODENAME /var/lib/tftpboot/$DISTRO-installer/$CODENAME.old
    mkdir /tmp/current-netboot-downloading-thingy
    cd /tmp/current-netboot-downloading-thingy
    tar xvzf /tmp/netboot.tar.gz
    rm /tmp/netboot.tar.gz
    mv /tmp/current-netboot-downloading-thingy/$DISTRO-installer/i386 /var/lib/tftpboot/$DISTRO-installer/$CODENAME
    rm -fr /tmp/current-netboot-downloading-thingy
done < "$config_file"

