#!/bin/sh
case $(hostname) in
  diskless*) 
    echo 10.2.2.22 ryukin >> /etc/hosts
    echo 10.2.2.14 gimpy >> /etc/hosts
    echo 10.2.2.17 dapper >> /etc/hosts
    echo 10.2.2.66 hardy >> /etc/hosts
    ;;
esac
