#!/bin/sh

# copyright 2007 Martin Chase <mchase@freegeek.org>, distributed
# under the terms of the GNU General Public License version 2 or any later
# version.

# Depends on xmms

tty=$(tty)
case "$tty" in
  /dev/tty*) # with udev (2.6 kernel)
      ttynum=${tty#/dev/tty}
      ;;
  /dev/vc/*) # with devfs (2.4 kernel)
      ttynum=${tty#/dev/vc/}
      ;;
esac

name="ltsp$ttynum-music"
logfile="/var/log/$name"
command="/usr/local/ass/configs/build/play-music"
opts="vt$ttynum"
daemon=/usr/bin/daemon
if [ -x "$daemon" ]; then
  exec "$daemon" --name="$name" --respawn -O $logfile -E $logfile -l $logfile -- $command $opts
else
  # run undaemonized. password prompting may not work
  exec $command $opts
fi
