Welcome to Ubuntu 7.04!

This is an installation netboot image for Ubuntu,
built on 20061102ubuntu26.

The default option is 'install'. For maximum
control, you can use the 'expert' option.

To install only the base system, use the 'server'
or 'server-expert' option.

If the system fails to boot at all (the typical
symptom is a white screen which doesn't go away),
use 'install video=ofonly', 'expert video=ofonly',
'server video=ofonly', or 'server-expert video=ofonly'.

Press the tab key for a list of options, or type
'help' for help.

************************************
If in doubt, just choose 'install', and if that 
doesn't work, try 'install video=ofonly'.
************************************
